import { Question, QuestionTopic } from '../questions'

export const englishVocabTopic: QuestionTopic = {
  id: 'english-vocab',
  displayName: 'English Vocabulary',
  questions: [
    // ── Grade 3 — difficulty 1 ────────────────────────────────────────────────
    {
      id: 'ev-g3-01',
      englishWord: 'fast',
      emoji: '🏃',
      hebrewHint: 'מהיר',
      options: ['גדול', 'מהיר', 'חלש', 'קטן'],
      correctIndex: 1,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-02',
      englishWord: 'slow',
      emoji: '🐢',
      hebrewHint: 'איטי',
      options: ['איטי', 'חזק', 'גבוה', 'אדום'],
      correctIndex: 0,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-03',
      englishWord: 'jump',
      emoji: '⬆️',
      hebrewHint: 'לקפוץ',
      options: ['לאכול', 'לישון', 'לקפוץ', 'לרוץ'],
      correctIndex: 2,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-04',
      englishWord: 'run',
      emoji: '💨',
      hebrewHint: 'לרוץ',
      options: ['לשחות', 'לרוץ', 'לשיר', 'לצחוק'],
      correctIndex: 1,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-05',
      englishWord: 'big',
      emoji: '🐘',
      hebrewHint: 'גדול',
      options: ['קטן', 'חדש', 'גדול', 'ישן'],
      correctIndex: 2,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-06',
      englishWord: 'small',
      emoji: '🐭',
      hebrewHint: 'קטן',
      options: ['גדול', 'קטן', 'חזק', 'מהיר'],
      correctIndex: 1,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-07',
      englishWord: 'strong',
      emoji: '💪',
      hebrewHint: 'חזק',
      options: ['חלש', 'איטי', 'חזק', 'קטן'],
      correctIndex: 2,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-08',
      englishWord: 'weak',
      emoji: '😔',
      hebrewHint: 'חלש',
      options: ['חזק', 'חלש', 'מהיר', 'גבוה'],
      correctIndex: 1,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-09',
      englishWord: 'fight',
      emoji: '⚔️',
      hebrewHint: 'להילחם',
      options: ['לברוח', 'לאכול', 'להילחם', 'לישון'],
      correctIndex: 2,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-10',
      englishWord: 'dodge',
      emoji: '🔄',
      hebrewHint: 'להתחמק',
      options: ['להתחמק', 'לתקוף', 'לקפוץ', 'לעצור'],
      correctIndex: 0,
      grade: 3,
      difficulty: 1,
    },

    // ── Grade 4 — difficulty 1–2 ──────────────────────────────────────────────
    {
      id: 'ev-g4-01',
      englishWord: 'summer',
      emoji: '☀️',
      hebrewHint: 'קיץ',
      options: ['חורף', 'אביב', 'קיץ', 'סתיו'],
      correctIndex: 2,
      grade: 4,
      difficulty: 1,
    },
    {
      id: 'ev-g4-02',
      englishWord: 'escape',
      emoji: '🚪',
      hebrewHint: 'לברוח',
      options: ['לתקוף', 'לנוח', 'לברוח', 'להילחם'],
      correctIndex: 2,
      grade: 4,
      difficulty: 1,
    },
    {
      id: 'ev-g4-03',
      englishWord: 'brave',
      emoji: '🦁',
      hebrewHint: 'אמיץ',
      options: ['פחדן', 'אמיץ', 'עצוב', 'עייף'],
      correctIndex: 1,
      grade: 4,
      difficulty: 1,
    },
    {
      id: 'ev-g4-04',
      englishWord: 'dangerous',
      emoji: '☠️',
      hebrewHint: 'מסוכן',
      options: ['בטוח', 'שקט', 'מסוכן', 'שמח'],
      correctIndex: 2,
      grade: 4,
      difficulty: 1,
    },
    {
      id: 'ev-g4-05',
      englishWord: 'heavy',
      emoji: '🏋️',
      hebrewHint: 'כבד',
      options: ['קל', 'כבד', 'מהיר', 'חדש'],
      correctIndex: 1,
      grade: 4,
      difficulty: 1,
    },
    {
      id: 'ev-g4-06',
      englishWord: 'enemy',
      emoji: '👹',
      hebrewHint: 'אויב',
      options: ['חבר', 'אויב', 'מורה', 'ספר'],
      correctIndex: 1,
      grade: 4,
      difficulty: 1,
    },
    {
      id: 'ev-g4-07',
      englishWord: 'shield',
      emoji: '🛡️',
      hebrewHint: 'מגן',
      options: ['חרב', 'קסדה', 'מגן', 'חץ'],
      correctIndex: 2,
      grade: 4,
      difficulty: 2,
    },
    {
      id: 'ev-g4-08',
      englishWord: 'wave',
      emoji: '🌊',
      hebrewHint: 'גל',
      options: ['ים', 'גל', 'שמיים', 'ענן'],
      correctIndex: 1,
      grade: 4,
      difficulty: 2,
    },
    {
      id: 'ev-g4-09',
      englishWord: 'power',
      emoji: '⚡',
      hebrewHint: 'כוח',
      options: ['חולשה', 'מהירות', 'כוח', 'אור'],
      correctIndex: 2,
      grade: 4,
      difficulty: 2,
    },
    {
      id: 'ev-g4-10',
      englishWord: 'dash',
      emoji: '💥',
      hebrewHint: 'לנוע בזריזות',
      options: ['לישון', 'לנוע בזריזות', 'לאכול', 'לשמוע'],
      correctIndex: 1,
      grade: 4,
      difficulty: 2,
    },

    // ── Grade 5 — difficulty 2 ────────────────────────────────────────────────
    {
      id: 'ev-g5-01',
      englishWord: 'defend',
      emoji: '🛡️',
      hebrewHint: 'להגן',
      options: ['לתקוף', 'להגן', 'לברוח', 'לצעוק'],
      correctIndex: 1,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-02',
      englishWord: 'score',
      emoji: '🏆',
      hebrewHint: 'ניקוד',
      options: ['שחקן', 'ניקוד', 'מפלה', 'זמן'],
      correctIndex: 1,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-03',
      englishWord: 'level',
      emoji: '📊',
      hebrewHint: 'רמה',
      options: ['ניקוד', 'גיל', 'רמה', 'מספר'],
      correctIndex: 2,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-04',
      englishWord: 'bonus',
      emoji: '🎁',
      hebrewHint: 'בונוס',
      options: ['קנס', 'בונוס', 'מחיר', 'חוב'],
      correctIndex: 1,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-05',
      englishWord: 'survive',
      emoji: '❤️',
      hebrewHint: 'לשרוד',
      options: ['למות', 'להפסיד', 'לשרוד', 'לנוח'],
      correctIndex: 2,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-06',
      englishWord: 'charge',
      emoji: '⚡',
      hebrewHint: 'לטעון / להתקיף',
      options: ['לעצור', 'לחכות', 'לטעון', 'לישון'],
      correctIndex: 2,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-07',
      englishWord: 'combo',
      emoji: '🔥',
      hebrewHint: 'שילוב מהלכים',
      options: ['מנוחה', 'שילוב מהלכים', 'ניקוד בסיס', 'הפסקה'],
      correctIndex: 1,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-08',
      englishWord: 'victory',
      emoji: '🏅',
      hebrewHint: 'ניצחון',
      options: ['תבוסה', 'ניצחון', 'שוויון', 'מאמץ'],
      correctIndex: 1,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-09',
      englishWord: 'defeat',
      emoji: '💀',
      hebrewHint: 'תבוסה',
      options: ['ניצחון', 'שוויון', 'תבוסה', 'הפסקה'],
      correctIndex: 2,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-10',
      englishWord: 'agile',
      emoji: '🐆',
      hebrewHint: 'זריז',
      options: ['איטי', 'כבד', 'זריז', 'עצבני'],
      correctIndex: 2,
      grade: 5,
      difficulty: 2,
    },

    // ── Grade 6 — difficulty 3 ────────────────────────────────────────────────
    {
      id: 'ev-g6-01',
      englishWord: 'invincible',
      emoji: '🌟',
      hebrewHint: 'בלתי מנוצח',
      options: ['חלש מאוד', 'בלתי מנוצח', 'מסוכן', 'מהיר מאוד'],
      correctIndex: 1,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-02',
      englishWord: 'devastating',
      emoji: '💣',
      hebrewHint: 'הרסני',
      options: ['עדין', 'הרסני', 'מועיל', 'שקט'],
      correctIndex: 1,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-03',
      englishWord: 'momentum',
      emoji: '🌀',
      hebrewHint: 'תנופה',
      options: ['עצירה', 'תנופה', 'מנוחה', 'שיווי משקל'],
      correctIndex: 1,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-04',
      englishWord: 'precision',
      emoji: '🎯',
      hebrewHint: 'דיוק',
      options: ['אקראיות', 'דיוק', 'מהירות', 'כוח'],
      correctIndex: 1,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-05',
      englishWord: 'overwhelm',
      emoji: '🌊',
      hebrewHint: 'להמם / לגבור',
      options: ['לנסוג', 'להמם', 'לשרוד', 'לנוח'],
      correctIndex: 1,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-06',
      englishWord: 'strategy',
      emoji: '♟️',
      hebrewHint: 'אסטרטגיה',
      options: ['כוח גס', 'אסטרטגיה', 'מזל', 'מהירות'],
      correctIndex: 1,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-07',
      englishWord: 'endure',
      emoji: '🧱',
      hebrewHint: 'לעמוד בפני / לסבול',
      options: ['לוותר', 'לעמוד בפני', 'לתקוף', 'להאיץ'],
      correctIndex: 1,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-08',
      englishWord: 'relentless',
      emoji: '⚙️',
      hebrewHint: 'בלתי נלאה',
      options: ['עייף', 'מפחד', 'בלתי נלאה', 'שקט'],
      correctIndex: 2,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-09',
      englishWord: 'ultimate',
      emoji: '👑',
      hebrewHint: 'אולטימטיבי / הכי חזק',
      options: ['רגיל', 'חלש', 'ממוצע', 'אולטימטיבי'],
      correctIndex: 3,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-10',
      englishWord: 'sacrifice',
      emoji: '🔥',
      hebrewHint: 'להקריב',
      options: ['להקריב', 'לחגוג', 'לנצח', 'לקבל'],
      correctIndex: 0,
      grade: 6,
      difficulty: 3,
    },

    // ── Extra questions — difficulty 1 (Grade 3, fallback pool) ───────────────
    {
      id: 'ev-g3-11',
      englishWord: 'happy',
      emoji: '😊',
      hebrewHint: 'שמח',
      options: ['עצוב', 'כועס', 'שמח', 'עייף'],
      correctIndex: 2,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-12',
      englishWord: 'water',
      emoji: '💧',
      hebrewHint: 'מים',
      options: ['אש', 'אוויר', 'עפר', 'מים'],
      correctIndex: 3,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-13',
      englishWord: 'win',
      emoji: '🏆',
      hebrewHint: 'לנצח',
      options: ['להפסיד', 'לנצח', 'לנוח', 'לאכול'],
      correctIndex: 1,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-14',
      englishWord: 'color',
      emoji: '🎨',
      hebrewHint: 'צבע',
      options: ['צורה', 'גודל', 'צבע', 'משקל'],
      correctIndex: 2,
      grade: 3,
      difficulty: 1,
    },
    {
      id: 'ev-g3-15',
      englishWord: 'power',
      emoji: '⚡',
      hebrewHint: 'כוח',
      options: ['אהבה', 'שמחה', 'ידע', 'כוח'],
      correctIndex: 3,
      grade: 3,
      difficulty: 1,
    },

    // ── Extra questions — difficulty 2 (Grade 4, fallback pool) ───────────────
    {
      id: 'ev-g4-11',
      englishWord: 'speed',
      emoji: '⚡',
      hebrewHint: 'מהירות',
      options: ['כוח', 'מהירות', 'גודל', 'כיוון'],
      correctIndex: 1,
      grade: 4,
      difficulty: 2,
    },
    {
      id: 'ev-g4-12',
      englishWord: 'dodge',
      emoji: '🔄',
      hebrewHint: 'להתחמק',
      options: ['לתקוף', 'להתחמק', 'לעמוד', 'לרוץ'],
      correctIndex: 1,
      grade: 4,
      difficulty: 2,
    },
    {
      id: 'ev-g4-13',
      englishWord: 'health',
      emoji: '❤️',
      hebrewHint: 'בריאות / חיים',
      options: ['בריאות', 'ניקוד', 'זמן', 'כוח'],
      correctIndex: 0,
      grade: 4,
      difficulty: 2,
    },
    {
      id: 'ev-g4-14',
      englishWord: 'arena',
      emoji: '⭕',
      hebrewHint: 'זירה',
      options: ['בית', 'גן', 'זירה', 'שוק'],
      correctIndex: 2,
      grade: 4,
      difficulty: 2,
    },
    {
      id: 'ev-g4-15',
      englishWord: 'launch',
      emoji: '🚀',
      hebrewHint: 'לשגר / להמריא',
      options: ['לנחות', 'לשגר', 'לעצור', 'להחביא'],
      correctIndex: 1,
      grade: 4,
      difficulty: 2,
    },

    // ── Extra questions — difficulty 2 (Grade 5, fallback pool) ───────────────
    {
      id: 'ev-g5-11',
      englishWord: 'energy',
      emoji: '🔋',
      hebrewHint: 'אנרגיה',
      options: ['עייפות', 'שקט', 'אנרגיה', 'כאב'],
      correctIndex: 2,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-12',
      englishWord: 'pulse',
      emoji: '💓',
      hebrewHint: 'פעימה / גל',
      options: ['פעימה', 'שקט', 'שינה', 'עצירה'],
      correctIndex: 0,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-13',
      englishWord: 'shadow',
      emoji: '🌑',
      hebrewHint: 'צל',
      options: ['אור', 'צל', 'ירח', 'כוכב'],
      correctIndex: 1,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-14',
      englishWord: 'target',
      emoji: '🎯',
      hebrewHint: 'מטרה',
      options: ['מקום', 'כלי', 'מטרה', 'נקודה'],
      correctIndex: 2,
      grade: 5,
      difficulty: 2,
    },
    {
      id: 'ev-g5-15',
      englishWord: 'flicker',
      emoji: '✨',
      hebrewHint: 'הבהוב',
      options: ['הבהוב', 'חשכה', 'קול', 'צבע'],
      correctIndex: 0,
      grade: 5,
      difficulty: 2,
    },

    // ── Extra questions — difficulty 3 (Grade 6, fallback pool) ───────────────
    {
      id: 'ev-g6-11',
      englishWord: 'resilient',
      emoji: '🌿',
      hebrewHint: 'עמיד / חסון',
      options: ['שביר', 'עמיד', 'איטי', 'עצוב'],
      correctIndex: 1,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-12',
      englishWord: 'lethal',
      emoji: '💀',
      hebrewHint: 'קטלני',
      options: ['קטלני', 'מרפא', 'חלש', 'איטי'],
      correctIndex: 0,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-13',
      englishWord: 'shockwave',
      emoji: '🌊',
      hebrewHint: 'גל הדף',
      options: ['רוח', 'גל הדף', 'ברק', 'עשן'],
      correctIndex: 1,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-14',
      englishWord: 'corrupt',
      emoji: '🖤',
      hebrewHint: 'מושחת',
      options: ['טהור', 'ישר', 'מושחת', 'בטוח'],
      correctIndex: 2,
      grade: 6,
      difficulty: 3,
    },
    {
      id: 'ev-g6-15',
      englishWord: 'operative',
      emoji: '🕵️',
      hebrewHint: 'סוכן',
      options: ['רופא', 'מורה', 'שחקן', 'סוכן'],
      correctIndex: 3,
      grade: 6,
      difficulty: 3,
    },
  ] as Question[],
}
